// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyWJRPyrqFN3PTOJpBptYvRbBvn62s-tc',
    appId: '1:656609955095:web:5eaf5747f5ee90dcc6fb52',
    messagingSenderId: '656609955095',
    projectId: 'fiesta-likes',
    authDomain: 'fiesta-likes.firebaseapp.com',
    storageBucket: 'fiesta-likes.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz5HatvoKnsYReO6K5mqaHNn0bfupx068',
    appId: '1:656609955095:android:bacbb493d461479dc6fb52',
    messagingSenderId: '656609955095',
    projectId: 'fiesta-likes',
    storageBucket: 'fiesta-likes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqQ3PbxdhKBy2aYRlooBOUrS5w-C5IcPs',
    appId: '1:656609955095:ios:2f24eaef19dbf9cac6fb52',
    messagingSenderId: '656609955095',
    projectId: 'fiesta-likes',
    storageBucket: 'fiesta-likes.firebasestorage.app',
    iosBundleId: 'com.example.fiestaLikes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqQ3PbxdhKBy2aYRlooBOUrS5w-C5IcPs',
    appId: '1:656609955095:ios:2f24eaef19dbf9cac6fb52',
    messagingSenderId: '656609955095',
    projectId: 'fiesta-likes',
    storageBucket: 'fiesta-likes.firebasestorage.app',
    iosBundleId: 'com.example.fiestaLikes',
  );
}
